project_id = "gqczgatkouxjdcyxnubf"

[functions.admin-users]
verify_jwt = false

[functions.register-provider]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.collision-public]
verify_jwt = false

